default: &global
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template1
  min_messages: warning
  username: federico
  host: 127.0.0.1

development:
  <<: *global
  database: webstripe_development

test:
  <<: *global
  database: webstripe_test

